### PR TITLE
Assorted tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@bezoerb please don't squash this!

Note that for some reason I always get a failure on Windows:

```
> postcss-discard@0.3.0 test C:\Users\xmr\Desktop\postcss-discard
> npm run xo && npm run jest


> postcss-discard@0.3.0 xo C:\Users\xmr\Desktop\postcss-discard
> xo


> postcss-discard@0.3.0 jest C:\Users\xmr\Desktop\postcss-discard
> jest

 FAIL  ./index.test.js
  √ removes css defined as string (298ms)
  × removes css defined as file (113ms)
  √ returns unchanged css (2ms)
  √ removes atrule (2ms)
  √ works regular expressions (2ms)
  √ removes everything (2ms)
  √ removes all rules (1ms)
  √ removes media queries width max-width: 768px (1ms)
  √ removes declarations by filter function (7ms)
  √ removes font-face && print (2ms)

  ● removes css defined as file

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    - .some-class {
    + .some-class,
    + .that-class {
        text-align: center;
    - }
    + }
    + .that-class {
    +   color: #b4d;
    + }
      ↵

      64 |       expect(result.warnings()).toHaveLength(0);
      65 |       if (output) {
    > 66 |         expect(result.css).toEqual(output);
         |                            ^
      67 |       }
      68 |
      69 |       return result;

      at toEqual (index.test.js:66:28)
          at async Promise.all (index 0)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 9 passed, 10 total
Snapshots:   0 total
Time:        1.477s, estimated 2s
Ran all test suites.

```

Not sure why.

**Comment by XhmikosR** [comment]
You should release a new patch version after this @bezoerb, ideally we should figure out why tests fail on Windows, but regardless of that, we get rid of a dep plus all vulnerabilities are fixes.

**Comment by XhmikosR** [comment]
Ping @bezoerb. I still don't get why tests fail on Windows, they always fail for me.

But this PR fixes all vulnerabilities, removes a useless dependency etc.

I think you should tackle the Windows issue after you merge this.

**Comment by bezoerb** [comment]
@XhmikosR: sorry for the delay. I’m quite busy at the moment. Hope i’ll find some time over the weekend

**Pull request merged**
