### PR TITLE
CI: switch to `actions/checkout@v2`

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Ping @bezoerb

**Comment by bezoerb** [comment]
@XhmikosR: Any idea why this is failing on windows node 6?

**Comment by XhmikosR** [comment]
It's unrelated, just restart the job and it should pass.

**Comment by bezoerb** [comment]
> It's unrelated, just restart the job and it should pass.

Restarted several times... keeps failing

**Comment by XhmikosR** [comment]
Yeah, but it can't be related...

**Comment by bezoerb** [comment]
Fixing the XO thing with another PR

**Pull request merged**
